export const MOONLIGHT_ANALYTICS_EVENTS = [
  'home_view',
  'premium_home_hero_primary_click',
  'premium_home_sample_click',
  'sample_report_start_click',
  'sample_report_engine_click',
  'report_decision_trace_open',
  'report_deep_report_click',
  'report_pdf_click',
  'report_dialogue_continue_click',
  'membership_report_card_click',
  'saju_start_viewed',
  'today_concern_selected',
  'birth_form_started',
  'birth_form_completed',
  'today_free_result_viewed',
  'premium_teaser_viewed',
  'unlock_clicked',
  'payment_started',
  'payment_completed',
  'premium_result_viewed',
  'saju_result_viewed',
  'followup_question_clicked',
  'dialogue_started_from_result',
  'feedback_submitted',
  'hit_memo_response_correct',
  'hit_memo_response_partial',
  'hit_memo_response_miss',
] as const;

export type MoonlightAnalyticsEvent = (typeof MOONLIGHT_ANALYTICS_EVENTS)[number];
